spring.application.name=BiblioTechProject
server.port=8081

# Your Cloud MongoDB Connection
spring.data.mongodb.uri=mongodb+srv://islembriki_db_user:q9fGNY3b2SN4c3Tb@cluster0.hgalebt.mongodb.net/bibliotech?retryWrites=true&w=majority&appName=Cluster0

# Show database activity in the console
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
# This tells Spring to actually create the Unique Index in MongoDB
spring.data.mongodb.auto-index-creation=true